version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: <USER>
      WORDPRESS_DB_PASSWORD: <PASSWORD>
      WORDPRESS_DB_NAME: mysql
    volumes:
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./html/:/var/www/html/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: <USER>
      MYSQL_PASSWORD: <PASSWORD>
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
